apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2019-01-18T09:53:43Z"
  generation: 1
  labels:
    app: thanhtien-test
  name: thanhtien-test
  namespace: default
  resourceVersion: "52839"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/thanhtien-test
  uid: f0f35ceb-1b06-11e9-a8a0-080027171c0c
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: thanhtien-test
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: thanhtien-test
    spec:
      containers:
      - image: tiennguyen123/thanhtien-test
        imagePullPolicy: Always
        name: thanhtien-test
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
          - name: REDIS_HOST
            value: "Warm greetings to"
          - name: REDIS_PORT
            value: "The Most Honorable"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2019-01-18T09:53:48Z"
    lastUpdateTime: "2019-01-18T09:53:48Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2019-01-18T09:53:43Z"
    lastUpdateTime: "2019-01-18T09:53:48Z"
    message: ReplicaSet "thanhtien-test-6df97f75bf" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1